  version: "2"
  services:
    nginx:
        build: ./nginx
        links:
            - node:node
        ports:
            - "3001:3001"
            - "35729:35729"
    node:
      build: .
      ports:
        - "3000"
        - "9229:9229"
      volumes:
        - .:/usr/src/app
      links:
        - mongodb  
        - redis
      environment:
        NODE_ENV: development 
        MONGODB_URI: mongodb://mongodb:27017 
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/data/log
        volumes:
          - ./data/db:/data/db
          - ./data/log:/data/log
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/data/log/log
    redis:
        image: redis
        ports:
            - "6379"