export enum ActionTypeKeys {
   
    ADD_CONFIGURATION = "ADD_CONFIGURATION",
    ADD_CONFIG_ENTITY = "ADD_CONFIG_ENTITY",
    UPDATE_ENTITY = "UPDATE_ENTITY",
    DELETE_ENTITY = "DELETE_ENTITY",

    OTHER_ACTION = "__any_other_action_type__"
}