export enum ActionTypeKeys {
   
    FETCH_CONFIGURATION = "FETCH_CONFIGURATION",
    FETCH_CONFIGURATION_SUCCESS = "FETCH_CONFIGURATION_SUCCESS",
    FETCH_CONFIGURATION_ERROR = "FETCH_CONFIGURATION_ERROR",
    ADD_CONFIGURATION = "ADD_CONFIGURATION",
    DELETE_CONFIGURATION = "DELETE_CONFIGURATION",

    ADD_ENTITY = "ADD_ENTITY",
    UPDATE_ENTITY = "UPDATE_ENTITY",
    DELETE_ENTITY = "DELETE_ENTITY",

    OTHER_ACTION = "__any_other_action_type__"
}